/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Modelo.Tema;
import Modelo.Foro;
import Modelo.Pregunta;
import Modelo.Universitario;
import controlador.Controlador;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nico2
 */
public class vistaHome extends javax.swing.JFrame {

    /**
     * Creates new form vistaHome
     */
    private Controlador controlador;
    private JFrame vistaAnterior;
    private Universitario universitario;
    
    public vistaHome() {
        initComponents();
        
    }

    public vistaHome(Controlador controlador, Universitario usuarioActual, vistaLogin aThis) {
       initComponents();
       this.controlador = controlador;
       this.universitario = usuarioActual;
       this.vistaAnterior = aThis;
       this.setLocationRelativeTo(null);
       this.labelApellido.setText(universitario.getApellido());
       this.labelNombre.setText(universitario.getNombre());
       this.labelLegajo.setText(universitario.getLegajo());
       this.labelTipo.setText(universitario.getTipo());
       
       //cargar lista temas
       List temas = controlador.buscarListaTemas();
       this.listaTemas.setListData(temas.toArray());
       //seleccionar tema por defecto
       if(temas.size()>0){
           this.listaTemas.setSelectedIndex(0);
       
       }
       
       if(universitario.getTipo().equals("ADMINISTRADOR")){//si es administrador puede ver los botones de agregar, eliminar foro
           this.botonAgregarForo.setVisible(true);
           this.botonEditarForo.setVisible(true);
       }else{
       
           this.botonAgregarForo.setVisible(false);
           this.botonEditarForo.setVisible(false);
       }
       
       this.actualizarListaForo();
       this.opcionTitulo.setSelected(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTemas = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaForos = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaPreguntas = new javax.swing.JList();
        botonAgregarForo = new javax.swing.JButton();
        botonAgregarPregunta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botonVerPregunta = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        labelAutor = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelForo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelTema = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        botonEditarForo = new javax.swing.JButton();
        botonActualizarPreguntas = new javax.swing.JButton();
        botonActualizarForo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        opcionForo = new javax.swing.JRadioButton();
        opcionCoincidencia = new javax.swing.JRadioButton();
        txtBuscar = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        opcionTitulo = new javax.swing.JRadioButton();
        opcionUsuario = new javax.swing.JRadioButton();
        txtUser = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        labelLegajo = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        botonVerUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 153));

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        listaTemas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaTemasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaTemas);

        listaForos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaForosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaForos);

        listaPreguntas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaPreguntasValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listaPreguntas);

        botonAgregarForo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-plus-math-26.png"))); // NOI18N
        botonAgregarForo.setBorder(null);
        botonAgregarForo.setContentAreaFilled(false);
        botonAgregarForo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarForoActionPerformed(evt);
            }
        });

        botonAgregarPregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-plus-math-26.png"))); // NOI18N
        botonAgregarPregunta.setBorder(null);
        botonAgregarPregunta.setContentAreaFilled(false);
        botonAgregarPregunta.setMaximumSize(new java.awt.Dimension(63, 39));
        botonAgregarPregunta.setMinimumSize(new java.awt.Dimension(63, 39));
        botonAgregarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPreguntaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        botonVerPregunta.setText("Ver Pregunta");
        botonVerPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerPreguntaActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripcion:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Detalles de pregunta:");

        jLabel9.setText("Titulo:");

        txtTitulo.setFocusable(false);

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setFocusable(false);
        jScrollPane4.setViewportView(txtDescripcion);

        jLabel10.setText("Autor:");

        labelAutor.setForeground(new java.awt.Color(102, 102, 102));
        labelAutor.setText("autor");

        jLabel11.setText("Fecha:");

        labelFecha.setForeground(new java.awt.Color(102, 102, 102));
        labelFecha.setText("fecha");

        jLabel12.setText("Foro:");

        labelForo.setForeground(new java.awt.Color(102, 102, 102));
        labelForo.setText("foro");

        jLabel13.setText("Tema:");

        labelTema.setForeground(new java.awt.Color(102, 102, 102));
        labelTema.setText("tema");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(botonVerPregunta))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(labelAutor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(labelFecha))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelForo)
                                    .addComponent(labelTema))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(labelAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labelFecha))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(labelForo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(labelTema))
                .addGap(18, 18, 18)
                .addComponent(botonVerPregunta)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Temas:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Foros:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Preguntas:");

        botonEditarForo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-edit-26.png"))); // NOI18N
        botonEditarForo.setBorder(null);
        botonEditarForo.setContentAreaFilled(false);
        botonEditarForo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarForoActionPerformed(evt);
            }
        });

        botonActualizarPreguntas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-actualizar-30.png"))); // NOI18N
        botonActualizarPreguntas.setBorder(null);
        botonActualizarPreguntas.setContentAreaFilled(false);
        botonActualizarPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarPreguntasActionPerformed(evt);
            }
        });

        botonActualizarForo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-actualizar-30.png"))); // NOI18N
        botonActualizarForo.setBorder(null);
        botonActualizarForo.setContentAreaFilled(false);
        botonActualizarForo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarForoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEditarForo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonActualizarForo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonAgregarForo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(51, 51, 51)
                        .addComponent(botonActualizarPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonAgregarPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 237, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addComponent(botonActualizarPreguntas))
                    .addComponent(botonAgregarPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(botonAgregarForo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonEditarForo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonActualizarForo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(21, 21, 21))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setForeground(new java.awt.Color(204, 255, 204));

        opcionForo.setBackground(new java.awt.Color(204, 255, 204));
        opcionForo.setText("Foro");
        opcionForo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opcionForoItemStateChanged(evt);
            }
        });

        opcionCoincidencia.setBackground(new java.awt.Color(204, 255, 204));
        opcionCoincidencia.setText("Coincidencia");
        opcionCoincidencia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opcionCoincidenciaItemStateChanged(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-search-30.png"))); // NOI18N
        botonBuscar.setBorder(null);
        botonBuscar.setContentAreaFilled(false);
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        opcionTitulo.setBackground(new java.awt.Color(204, 255, 204));
        opcionTitulo.setText("Titulo");
        opcionTitulo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opcionTituloItemStateChanged(evt);
            }
        });

        opcionUsuario.setBackground(new java.awt.Color(204, 255, 204));
        opcionUsuario.setText("Usuario");
        opcionUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opcionUsuarioItemStateChanged(evt);
            }
        });

        txtUser.setText("Ingrese el usuario");
        txtUser.setEnabled(false);
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(opcionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(opcionTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(opcionCoincidencia)
                            .addGap(26, 26, 26)
                            .addComponent(opcionForo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(txtBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(botonBuscar)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionForo)
                    .addComponent(opcionCoincidencia)
                    .addComponent(opcionTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcionUsuario)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BitNet");

        labelNombre.setText("tuNombre");

        labelApellido.setText("tuApellido");

        labelLegajo.setText("tuLegajo");

        labelTipo.setText("(tipo)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(labelApellido)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(labelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelLegajo)
                            .addComponent(labelNombre))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLegajo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));

        botonVerUsuarios.setText("Ver Usuarios");
        botonVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(botonVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(botonVerUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void botonVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerUsuariosActionPerformed
        // abre la ventana de ver usuarios
        vistaVerUsuarios vistaUser = new vistaVerUsuarios(controlador,universitario,this);
        vistaUser.setVisible(true);
        
        
        
    }//GEN-LAST:event_botonVerUsuariosActionPerformed

    private void botonAgregarForoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarForoActionPerformed
        // boton agregar un nuevo foro, para el administrador. se abre nueva ventana para hacerlo.
        if(!this.listaTemas.isSelectionEmpty()){//si selecciono un tema
            vistaAgregarForo foroNuevo = new vistaAgregarForo (controlador,universitario,this, (Tema) listaTemas.getSelectedValue());
            foroNuevo.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "seleccione el tema para crear un foro");
        }
        
    }//GEN-LAST:event_botonAgregarForoActionPerformed

    private void listaTemasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaTemasValueChanged
        // al seleccionar un tema de la lista , la lista del medio muestra los foros relacionados al tema
        actualizarListaForo();
        
    }//GEN-LAST:event_listaTemasValueChanged

    private void botonActualizarForoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarForoActionPerformed
        // al seleccionar actualiza la lista siempre que tenga algo seleccionado
        if(!this.listaTemas.isSelectionEmpty()){
            actualizarListaForo();
        }else{
        
             JOptionPane.showMessageDialog(null, "Debe seleccionar un tema");
        }
        
    }//GEN-LAST:event_botonActualizarForoActionPerformed

    private void listaForosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaForosValueChanged
        // al seleccionar un  foro, la lista de reguntas debe actualizar lo que tiene
        actualizarListaPreguntas();
        
    }//GEN-LAST:event_listaForosValueChanged

    private void botonActualizarPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarPreguntasActionPerformed
        // boton que actualiza la lista de preguntas, siempre que un tema este seleccionado
        if(!this.listaForos.isSelectionEmpty()){
            actualizarListaPreguntas();
        }else{
        
             JOptionPane.showMessageDialog(null, "Debe seleccionar un Foro");
        }
        
        
    }//GEN-LAST:event_botonActualizarPreguntasActionPerformed

    private void botonAgregarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPreguntaActionPerformed
        // se abre una ventana nueva para crear una pregunta
        if(!this.listaForos.isSelectionEmpty()){//si selecciono un tema
            vistaAgregarPregunta preguntaNueva = new vistaAgregarPregunta (controlador,universitario,this, (Foro) listaForos.getSelectedValue());
            preguntaNueva.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "seleccione el foro para crear una pregunta");
        }
        
        
    }//GEN-LAST:event_botonAgregarPreguntaActionPerformed

    private void listaPreguntasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaPreguntasValueChanged
        // al seleccionar una pregunta se muestran sus datos
        if(!this.listaPreguntas.isSelectionEmpty()){
            Pregunta p1 = (Pregunta) listaPreguntas.getSelectedValue();
            this.txtTitulo.setText(p1.getTitulo());
            this.txtDescripcion.setText(p1.getDescripcion());
            this.labelTema.setText(p1.getForo().getTema().toString());
            this.labelAutor.setText(p1.getUniversitario().getApellido() + " " + p1.getUniversitario().getNombre());
            this.labelFecha.setText(p1.getFecha().toString());
            this.labelForo.setText(p1.getForo().toString());
        }
        
        
        
        
    }//GEN-LAST:event_listaPreguntasValueChanged

    private void botonVerPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerPreguntaActionPerformed
        // boton de ver la pregunta, si se lecciono una pregunta se abre una ventana nueva para ver la pregunta
        if(!this.listaPreguntas.isSelectionEmpty()){
            Pregunta p1 = (Pregunta) listaPreguntas.getSelectedValue();
            vistaVerPregunta verPregunta = new vistaVerPregunta (controlador,universitario,this,p1);
            verPregunta.setVisible(true);
            
        }else{
        
            JOptionPane.showMessageDialog(null, "seleccione una pregunta");
        
        }
        
       
        
    }//GEN-LAST:event_botonVerPreguntaActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // boton de buscar comprueba todos los parametros y le pide al controlador las preguntas
        //segun los parametros enviados
        //luego de revibir la lista de preguntas, se muestran en pantalla
        String textoBuscado = this.txtBuscar.getText();
        String nomUser = this.txtUser.getText();
        boolean critUser = this.opcionUsuario.isSelected();
        boolean critCoinci = this.opcionCoincidencia.isSelected();
        Tema unTema = (Tema) this.listaTemas.getSelectedValue();
        Foro unForo;
        if(!this.listaForos.isSelectionEmpty() && this.opcionForo.isSelected()){
            unForo = (Foro) this.listaForos.getSelectedValue();
        }else{
            unForo = null;
        }
        
        
        
        if(this.txtBuscar.getText().isEmpty()){
            if(this.opcionUsuario.isSelected()){
                this.listaPreguntas.setListData(controlador.realizarBusqueda(textoBuscado,nomUser,critUser,critCoinci,unTema,unForo).toArray());
                
                
            }else{
            
                JOptionPane.showMessageDialog(null, "si deja vacio el campo de busqueda se buscara todas las preguntas del usuario, por favor inserte un usuario");
            }
            
            
        }else{
        
            this.listaPreguntas.setListData(controlador.realizarBusqueda(textoBuscado,nomUser,critUser,critCoinci,unTema,unForo).toArray());
        
        }
        
        
        
        
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void opcionCoincidenciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opcionCoincidenciaItemStateChanged
        // hay un cambio en la seleccion de coincidencia
        if(this.opcionCoincidencia.isSelected()){//esta seleccionado
            //deseleccionar titulo
            this.opcionTitulo.setSelected(false);
        
        
        
        }else{
            //seleccionar titulo
            this.opcionTitulo.setSelected(true);
        
        }
    }//GEN-LAST:event_opcionCoincidenciaItemStateChanged

    private void opcionTituloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opcionTituloItemStateChanged
        // hay un cambio en la seleccion de titulo
        if(this.opcionTitulo.isSelected()){//esta seleccionado
            //deseleccionar coincidencia
            this.opcionCoincidencia.setSelected(false);
        
        
        
        }else{
            //seleccionar coincidencia
            this.opcionCoincidencia.setSelected(true);
        
        }
    }//GEN-LAST:event_opcionTituloItemStateChanged

    private void opcionForoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opcionForoItemStateChanged
        // el cambiar el estado de foro
        if(this.opcionForo.isSelected()){
            if(this.listaForos.isSelectionEmpty()){//si no esta seleccionado un foro?
                
                JOptionPane.showMessageDialog(null, "seleccione una foro primero");
                this.opcionForo.setSelected(false);
            }
        
        
        }
    }//GEN-LAST:event_opcionForoItemStateChanged

    private void opcionUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opcionUsuarioItemStateChanged
        // cambia el estado de la seleccion usuario
        if(this.opcionUsuario.isSelected()){
            this.txtUser.setEnabled(true);
        
        }else{
            this.txtUser.setEnabled(false);
            this.txtUser.setText("Ingrese el usuario");
        
        
        }
        
    }//GEN-LAST:event_opcionUsuarioItemStateChanged

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        // cuando el campo de ingreso del usuario gana el foco de atencion, se borra el texto "ingrese usuario"
        if(this.txtUser.getText().equals("Ingrese el usuario")){
            this.txtUser.setText("");
        }
    }//GEN-LAST:event_txtUserFocusGained

    private void botonEditarForoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarForoActionPerformed
        if(!this.listaForos.isSelectionEmpty() && !this.listaForos.isSelectionEmpty()){//si selecciono un tema
            vistaAgregarForo editarForo = new vistaAgregarForo (controlador,universitario,this, (Foro) listaForos.getSelectedValue());
            editarForo.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "seleccione el foro para editar");
        }
    }//GEN-LAST:event_botonEditarForoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarForo;
    private javax.swing.JButton botonActualizarPreguntas;
    private javax.swing.JButton botonAgregarForo;
    private javax.swing.JButton botonAgregarPregunta;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEditarForo;
    private javax.swing.JToggleButton botonVerPregunta;
    private javax.swing.JButton botonVerUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelForo;
    private javax.swing.JLabel labelLegajo;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTema;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JList listaForos;
    private javax.swing.JList listaPreguntas;
    private javax.swing.JList listaTemas;
    private javax.swing.JRadioButton opcionCoincidencia;
    private javax.swing.JRadioButton opcionForo;
    private javax.swing.JRadioButton opcionTitulo;
    private javax.swing.JRadioButton opcionUsuario;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    public void actualizarListaForo() {
        if(!this.listaTemas.isSelectionEmpty()){
        
            Tema unTema = (Tema) listaTemas.getSelectedValue();
            this.listaForos.setListData(controlador.verForo(unTema).toArray());
            List auxList = new ArrayList<>();
            this.listaPreguntas.setListData(auxList.toArray());
            this.limpiarPreguntaSeleccionada();
            this.opcionForo.setSelected(false);
        
        }
    }

    private void actualizarListaPreguntas() {
        if(!this.listaForos.isSelectionEmpty()){
        
            Foro auxForo = (Foro) listaForos.getSelectedValue();
            this.listaPreguntas.setListData(controlador.buscarPreguntasDeForo(auxForo).toArray());
            this.limpiarPreguntaSeleccionada();
        
        }
    }
    private void limpiarPreguntaSeleccionada(){
        this.txtTitulo.setText("");
        this.txtDescripcion.setText("");
        this.labelTema.setText("");
        this.labelAutor.setText("");
        this.labelFecha.setText("");
        this.labelForo.setText("");
    
    
    }
}
